GENERAL_QUESTIONS = [
    "What causes a sore throat?",
    "What are the symptoms of flu?",
    "What is the difference between cold and flu?",
    "What are signs of dehydration?",
    "Why do I feel dizzy?",
    "What are early symptoms of diabetes?",
    "What are common signs of high blood pressure?",
    "Why do I have frequent headaches?",
    "What does chest pain indicate?",
    "What are symptoms of anemia?",
    "What is paracetamol used for?",
    "What are side effects of ibuprofen?",
    "Can I take aspirin and paracetamol together?",
    "What are the uses of antibiotics?",
    "What is the difference between generic and brand-name medicines?",
    "What is the usual dosage for amoxicillin?",
    "Are antacids safe during pregnancy?",
    "What is a CBC blood test?",
    "What does an X-ray show?",
    "What is an MRI scan used for?",
    "What is a normal blood pressure range?",
    "What is considered a high cholesterol level?",
    "What are signs of anxiety?",
    "How to manage stress naturally?",
    "What is depression and its symptoms?",
    "How does therapy help with mental health?",
    "Are mood swings normal?",
    "What is a balanced diet?",
    "How much water should I drink daily?",
    "How many hours of sleep should I get?",
    "What are the benefits of regular exercise?",
    "What foods help boost immunity?",
    "What is a colonoscopy?",
    "Is general anesthesia safe?",
    "How do vaccinations work?",
    "What happens during a root canal?",
    "What is a CT scan?",
    "What should I do if someone faints?",
    "How do I treat a minor burn at home?",
    "What is CPR?",
    "How do I stop a nosebleed?",
    "What to do in case of a bee sting?",
    "What is a normal temperature for a baby?",
    "What are common childhood vaccines?",
    "When does teething usually start?",
    "How do I treat diaper rash?",
    "What is PMS?",
    "How long is a normal menstrual cycle?",
    "What are early signs of pregnancy?",
    "Is it normal to have irregular periods?",
    "What are symptoms of PCOS?",
    "What are early signs of Alzheimer’s?",
    "How to prevent falls in older adults?",
    "What is osteoporosis?",
    "What are the nutritional needs for seniors?",
    "What are the symptoms of COVID-19?",
    "What to do if you test positive for COVID-19?",
    "How does the immune system work?",
    "What is a healthy BMI range?",
    "What are good habits for heart health?",
    "What causes high cholesterol?",
    "What is insulin and how does it work?",
    "What are the common side effects of vaccines?",
    "What does a healthy poop look like?",
    "Can stress cause physical illness?",
    "What causes muscle cramps?",
    "Why do I get leg pain at night?",
    "What are common causes of back pain?",
    "How to relieve eye strain from screens?",
    "What are common allergies?",
    "How to treat seasonal allergies?",
    "Can dehydration cause headaches?",
    "What is a fever and when is it serious?"
]
